[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Nepal-College-of-Information-Technology/AI-Data-Science-Worksop-2024/blob/main/Practice%20Yourself/Assignment_3.1_NumPy.ipynb)

# NumPy Assignment

This assignment consists of 10 tasks designed to help you practice NumPy operations. The tasks are divided into three levels of difficulty: easy, medium, and challenging.

---

## Easy Tasks:

### **Task 1**: Create a 1D NumPy array with the numbers from 1 to 10 and print it.


In [2]:
import numpy as np
array_1d = np.array([10, 20, 30, 40])

print("1D Array:", array_1d)

1D Array: [10 20 30 40]


### **Task 2:** Create a 2D NumPy array with 2 rows and 3 columns containing any numbers of your choice.

In [5]:
import numpy as np
array_2d = np.array([[10, 20, 30], [40, 50, 60]])

print("2D array with 2 rows and 3 columns: \n", array_2d)

2D array with 2 rows and 3 columns: 
 [[10 20 30]
 [40 50 60]]


### **Task 3:** Create an array of zeros with a shape of (4, 4) and print it.

In [6]:
import numpy as np
array = np.array([[0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0]])

print("array: \n", array)


array: 
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## Medium-Level Tasks:

### **Task 4:** Create a 1D array with the numbers from 1 to 100, and print the sum and mean of the array.

In [8]:
import numpy as np
array = np.arange(1, 101)

print("The required array is:\n", array)

The required array is:
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


### **Task 5:** Create a 5x5 identity matrix using NumPy.

In [9]:
import numpy as np
array = np.array([[1,0,0,0,0], [0,1,0,0,0], [0,0,1,0,0], [0,0,0,1,0], [0,0,0,0,1]])

print(" 5x5 identity matrix is: \n", array)

 5x5 identity matrix is: 
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### **Task 6:** Reshape a 1D array of numbers from 1 to 12 into a 3x4 matrix.

In [11]:
import numpy as np
array_1d = np.arange(1, 13)

matrix_3x4 = array_1d.reshape(3, 4)

print("3*4 matrix is: \n", matrix_3x4)




3*4 matrix is: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### **Task 7:** Create two 1D arrays with 5 random numbers each and print the result of element-wise addition.

In [13]:
import numpy as np
array_1 = np.array([2, 4, 6, 8, 10])
array_2 = np.array([1, 5, 2, 2, 10])

array_addition = array_1 + array_2

print("first array:", array_1)
print("second array:", array_2)
print("The addition of two array is:", array_addition)

first array: [ 2  4  6  8 10]
second array: [ 1  5  2  2 10]
The addition of two array is: [ 3  9  8 10 20]


## Challenging Tasks:

### **Task 8:** Generate a 3x3 matrix with random integers between 1 and 100. Print the maximum, minimum, and sum of all the elements.

In [18]:
import numpy as np
array3x3 = np.array([[2, 4, 6], [20, 50, 90], [1, 10, 7]])

#foe maximum and minimum
max_value = np.max(array3x3)
min_value = np.min(array3x3)

#print
print("Array:", array3x3)
print("Maximum value:", max_value)
print("Minimum value:", min_value)


Array: [[ 2  4  6]
 [20 50 90]
 [ 1 10  7]]
Maximum value: 90
Minimum value: 1


### **Task 9:** Create a 4x4 matrix and replace all the values in the diagonal with 1 (without using identity matrix functions).

In [19]:
import numpy as np

array4x4 = np.array([[7, 2, 3, 4], [44, 50, 8, 99], [77, 1, 55, 69], [10, 70, 6, 9]])

for i in range(4):
  array4x4 [i, i] =1

print("The final matrix is: \n", array4x4 )

The final matrix is: 
 [[ 1  2  3  4]
 [44  1  8 99]
 [77  1  1 69]
 [10 70  6  1]]


### **Task 10:** Create an array of 100 random numbers and compute the mean, standard deviation, and variance of the array.

In [21]:
import numpy as np
random_array = np.random.rand(100)

# for mean
mean = np.mean(random_array)

# for standard deviation
deviation = np.std(random_array)

#for variance
variance = np.var(random_array)

#print
print("Rando array: \n", random_array)
print("mean:", mean)
print("standard deviation:", deviation)
print("Variance:", variance)

Rando array: 
 [0.69566529 0.40547883 0.38873557 0.19041071 0.20765716 0.05176056
 0.31304015 0.00671989 0.32288917 0.37421515 0.59864027 0.18968506
 0.09042316 0.48496822 0.17695951 0.45776665 0.19555347 0.84704304
 0.84270063 0.4815893  0.20122594 0.22494752 0.54780959 0.31384826
 0.6448516  0.183859   0.77018514 0.01734674 0.05285269 0.97878143
 0.83424346 0.55764017 0.88618868 0.28645646 0.80788651 0.22027799
 0.83552216 0.35624558 0.90369964 0.629783   0.49932568 0.58353848
 0.01367545 0.5345996  0.06720507 0.54965666 0.7290864  0.83534888
 0.73441881 0.74009206 0.31383296 0.09077349 0.64598207 0.59838128
 0.09993717 0.9984458  0.56844031 0.749634   0.94279171 0.78719326
 0.18371302 0.13666486 0.65804605 0.80278127 0.41296009 0.69792001
 0.43834423 0.83204869 0.61258314 0.37276019 0.85017497 0.69175363
 0.11512118 0.58160586 0.28086444 0.21187894 0.81192662 0.44234608
 0.17306981 0.13001912 0.43610062 0.50916791 0.79916679 0.17093389
 0.86736742 0.85338666 0.41275341 0.16484464 0.

---